services:
  app:
    image: app-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ..:/workspace:cached
    environment:
      - NODE_ENV=development
      - PORT=3000
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-testing332211222111}
    tty: true
    stdin_open: true

